// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TicketsAPI.Data;

#nullable disable

namespace TicketsAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TicketsAPI.Models.Cas", b =>
                {
                    b.Property<string>("IdCas")
                        .HasColumnType("text")
                        .HasColumnName("ID_cas");

                    b.Property<string>("Celular")
                        .HasColumnType("text")
                        .HasColumnName("Celular");

                    b.Property<string>("Celular2")
                        .HasColumnType("text")
                        .HasColumnName("Celular_2");

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("text")
                        .HasColumnName("Correo_electronico");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Creado_el");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("text")
                        .HasColumnName("Creado_por");

                    b.Property<string>("Departamento")
                        .HasColumnType("text")
                        .HasColumnName("Departamento");

                    b.Property<string>("Distrito")
                        .HasColumnType("text")
                        .HasColumnName("Distrito");

                    b.Property<string>("Logo")
                        .HasColumnType("text")
                        .HasColumnName("Logo");

                    b.Property<DateTime?>("ModificadoEl")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Modificado_el");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("text")
                        .HasColumnName("Modificado_por");

                    b.Property<string>("PaisRegion")
                        .HasColumnType("text")
                        .HasColumnName("Pais_Region");

                    b.Property<string>("Provincia")
                        .HasColumnType("text")
                        .HasColumnName("Provincia");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("text")
                        .HasColumnName("Razon_social");

                    b.Property<string>("Ruc")
                        .HasColumnType("text")
                        .HasColumnName("Ruc");

                    b.Property<string>("TelefonoFijo")
                        .HasColumnType("text")
                        .HasColumnName("Telefono_fijo");

                    b.HasKey("IdCas");

                    b.ToTable("GACP_APP_TB_CAS");
                });

            modelBuilder.Entity("TicketsAPI.Models.Cliente", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text")
                        .HasColumnName("ID_cliente");

                    b.Property<string>("Apellido")
                        .HasColumnType("text")
                        .HasColumnName("Apellido");

                    b.Property<string>("Celular")
                        .HasColumnType("text")
                        .HasColumnName("Celular");

                    b.Property<string>("Celular2")
                        .HasColumnType("text")
                        .HasColumnName("Celular_2");

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("text")
                        .HasColumnName("Correo_electronico");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Creado_el");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("text")
                        .HasColumnName("Creado_por");

                    b.Property<string>("Departamento")
                        .HasColumnType("text")
                        .HasColumnName("Departamento");

                    b.Property<string>("Distrito")
                        .HasColumnType("text")
                        .HasColumnName("Distrito");

                    b.Property<DateTime?>("ModificadoEl")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Modificado_el");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("text")
                        .HasColumnName("Modificado_por");

                    b.Property<string>("Moroso")
                        .HasColumnType("text")
                        .HasColumnName("Moroso");

                    b.Property<string>("Nacionalidad")
                        .HasColumnType("text")
                        .HasColumnName("Nacionalidad");

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.Property<string>("NombreVia")
                        .HasColumnType("text")
                        .HasColumnName("Nombre_via");

                    b.Property<string>("NombreZona")
                        .HasColumnType("text")
                        .HasColumnName("Nombre_zona");

                    b.Property<string>("NroIntDpto")
                        .HasColumnType("text")
                        .HasColumnName("Nro_int_dpto");

                    b.Property<string>("Numero")
                        .HasColumnType("text")
                        .HasColumnName("Numero");

                    b.Property<string>("NumeroDocumento")
                        .HasColumnType("text")
                        .HasColumnName("Numero_documento");

                    b.Property<string>("PaisRegion")
                        .HasColumnType("text")
                        .HasColumnName("Pais_Region");

                    b.Property<string>("PaisRegionFiscal")
                        .HasColumnType("text")
                        .HasColumnName("Pais_region_fiscal");

                    b.Property<string>("Provincia")
                        .HasColumnType("text")
                        .HasColumnName("Provincia");

                    b.Property<string>("Referencia")
                        .HasColumnType("text")
                        .HasColumnName("Referencia");

                    b.Property<string>("ReferenciaAdicional")
                        .HasColumnType("text")
                        .HasColumnName("Referencia_adicional");

                    b.Property<string>("TelefonoFijo")
                        .HasColumnType("text")
                        .HasColumnName("Telefono_fijo");

                    b.Property<string>("TipoDocumento")
                        .HasColumnType("text")
                        .HasColumnName("Tipo_documento");

                    b.Property<string>("Zona")
                        .HasColumnType("text")
                        .HasColumnName("Zona");

                    b.HasKey("ID");

                    b.ToTable("GACP_APP_TB_CLIENTES", (string)null);
                });

            modelBuilder.Entity("TicketsAPI.Models.Departamento", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("Id");

                    b.Property<string>("NombreDepartamento")
                        .HasColumnType("text")
                        .HasColumnName("Departamento");

                    b.Property<string>("Pais")
                        .HasColumnType("text")
                        .HasColumnName("Pais");

                    b.HasKey("Id");

                    b.ToTable("GACP_APP_TB_DEPARTAMENTO");
                });

            modelBuilder.Entity("TicketsAPI.Models.Distrito", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("Id");

                    b.Property<string>("Departamento")
                        .HasColumnType("text")
                        .HasColumnName("Departamento");

                    b.Property<string>("NombreDistrito")
                        .HasColumnType("text")
                        .HasColumnName("Distrito");

                    b.Property<string>("Pais")
                        .HasColumnType("text")
                        .HasColumnName("Pais");

                    b.Property<string>("Provincia")
                        .HasColumnType("text")
                        .HasColumnName("Provincia");

                    b.HasKey("Id");

                    b.ToTable("GACP_APP_TB_DISTRITO");
                });

            modelBuilder.Entity("TicketsAPI.Models.Empleado", b =>
                {
                    b.Property<string>("IdEmpleado")
                        .HasColumnType("text")
                        .HasColumnName("ID_empleado");

                    b.Property<string>("Apellido")
                        .HasColumnType("text")
                        .HasColumnName("Apellido");

                    b.Property<string>("Area")
                        .HasColumnType("text")
                        .HasColumnName("Area");

                    b.Property<string>("Cargo")
                        .HasColumnType("text")
                        .HasColumnName("Cargo");

                    b.Property<string>("Celular")
                        .HasColumnType("text")
                        .HasColumnName("Celular");

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("text")
                        .HasColumnName("Correo_electronico");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Creado_el");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("text")
                        .HasColumnName("Creado_por");

                    b.Property<DateTime?>("ModificadoEl")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Modificado_el");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("text")
                        .HasColumnName("Modificado_por");

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.Property<string>("NumeroDocumento")
                        .HasColumnType("text")
                        .HasColumnName("Numero_documento");

                    b.Property<string>("TipoDocumento")
                        .HasColumnType("text")
                        .HasColumnName("Tipo_documento");

                    b.HasKey("IdEmpleado");

                    b.ToTable("GACP_APP_TB_EMPLEADOS");
                });

            modelBuilder.Entity("TicketsAPI.Models.InformeTecnico", b =>
                {
                    b.Property<string>("IdInformeTecnico")
                        .HasColumnType("text")
                        .HasColumnName("ID_informe_tecnico");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Creado_el");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("text")
                        .HasColumnName("Creado_por");

                    b.Property<string>("Estado")
                        .HasColumnType("text")
                        .HasColumnName("Estado");

                    b.Property<string>("FirmaCliente")
                        .HasColumnType("text")
                        .HasColumnName("Firma_cliente");

                    b.Property<string>("FirmaTecnico")
                        .HasColumnType("text")
                        .HasColumnName("Firma_tecnico");

                    b.Property<DateTime?>("ModificadoEl")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Modificado_el");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("text")
                        .HasColumnName("Modificado_por");

                    b.Property<string>("ObservacionesTecnico")
                        .HasColumnType("text")
                        .HasColumnName("Observaciones_tecnico");

                    b.Property<string>("SerieProducto")
                        .HasColumnType("text")
                        .HasColumnName("Serie_producto");

                    b.Property<string>("Ticket")
                        .HasColumnType("text")
                        .HasColumnName("Ticket");

                    b.Property<string>("TrabajoEfectuado")
                        .HasColumnType("text")
                        .HasColumnName("Trabajo_efectuado");

                    b.Property<string>("VisitaRealizada")
                        .HasColumnType("text")
                        .HasColumnName("Visita_realizada");

                    b.HasKey("IdInformeTecnico");

                    b.ToTable("GACP_APP_TB_INFORME_TECNICO");
                });

            modelBuilder.Entity("TicketsAPI.Models.Material", b =>
                {
                    b.Property<string>("IdMaterial")
                        .HasColumnType("text")
                        .HasColumnName("ID_Material");

                    b.Property<string>("Categoria")
                        .HasColumnType("text")
                        .HasColumnName("Categoria");

                    b.Property<string>("Descuento")
                        .HasColumnType("text")
                        .HasColumnName("Descuento");

                    b.Property<string>("Estado")
                        .HasColumnType("text")
                        .HasColumnName("Estado");

                    b.Property<string>("EstadoEnCatalogo")
                        .HasColumnType("text")
                        .HasColumnName("EstadoEnCatalogo");

                    b.Property<string>("Garantia")
                        .HasColumnType("text")
                        .HasColumnName("Garantia");

                    b.Property<string>("IdExterno")
                        .HasColumnType("text")
                        .HasColumnName("ID_Externo");

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.Property<string>("Sector")
                        .HasColumnType("text")
                        .HasColumnName("Sector");

                    b.Property<string>("UnidadMedida")
                        .HasColumnType("text")
                        .HasColumnName("Unidad_medida");

                    b.Property<string>("Uso")
                        .HasColumnType("text")
                        .HasColumnName("Uso");

                    b.HasKey("IdMaterial");

                    b.ToTable("GAC_APP_TB_MATERIALES", (string)null);
                });

            modelBuilder.Entity("TicketsAPI.Models.ProductoRegistrado", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("ID");

                    b.Property<string>("CategoriaProductoRegistrado")
                        .HasColumnType("text")
                        .HasColumnName("Categoria_producto_registrado");

                    b.Property<string>("Cliente")
                        .HasColumnType("text")
                        .HasColumnName("Cliente");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Creado_el");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("text")
                        .HasColumnName("Creado_por");

                    b.Property<string>("Departamento")
                        .HasColumnType("text")
                        .HasColumnName("Departamento");

                    b.Property<string>("Distrito")
                        .HasColumnType("text")
                        .HasColumnName("Distrito");

                    b.Property<string>("EdificioPlantaSala")
                        .HasColumnType("text")
                        .HasColumnName("Edificio_planta_sala");

                    b.Property<string>("Garantia")
                        .HasColumnType("text")
                        .HasColumnName("Garantia");

                    b.Property<string>("Latitud")
                        .HasColumnType("text")
                        .HasColumnName("Latitud");

                    b.Property<string>("Longitud")
                        .HasColumnType("text")
                        .HasColumnName("Longitud");

                    b.Property<string>("LugarCompra")
                        .HasColumnType("text")
                        .HasColumnName("Lugar_compra");

                    b.Property<DateTime?>("ModificadoEl")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Modificado_el");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("text")
                        .HasColumnName("Modificado_por");

                    b.Property<string>("NombreVia")
                        .HasColumnType("text")
                        .HasColumnName("Nombre_via");

                    b.Property<string>("NombreZona")
                        .HasColumnType("text")
                        .HasColumnName("Nombre_zona");

                    b.Property<string>("Numero")
                        .HasColumnType("text")
                        .HasColumnName("Numero");

                    b.Property<string>("PaisRegion")
                        .HasColumnType("text")
                        .HasColumnName("Pais_region");

                    b.Property<string>("Producto")
                        .HasColumnType("text")
                        .HasColumnName("Producto");

                    b.Property<string>("Provincia")
                        .HasColumnType("text")
                        .HasColumnName("Provincia");

                    b.Property<string>("Referencia")
                        .HasColumnType("text")
                        .HasColumnName("Referencia");

                    b.Property<string>("Zona")
                        .HasColumnType("text")
                        .HasColumnName("Zona");

                    b.HasKey("Id");

                    b.ToTable("GACP_APP_TB_PRODUCTO_REGISTRADO", (string)null);
                });

            modelBuilder.Entity("TicketsAPI.Models.Provincia", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("Id");

                    b.Property<string>("Departamento")
                        .HasColumnType("text")
                        .HasColumnName("Departamento");

                    b.Property<string>("NombreProvincia")
                        .HasColumnType("text")
                        .HasColumnName("Provincia");

                    b.Property<string>("Pais")
                        .HasColumnType("text")
                        .HasColumnName("Pais");

                    b.HasKey("Id");

                    b.ToTable("GACP_APP_TB_PROVINCIA");
                });

            modelBuilder.Entity("TicketsAPI.Models.Ticket", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text")
                        .HasColumnName("ID");

                    b.Property<string>("Ayudante")
                        .HasColumnType("text")
                        .HasColumnName("Ayudante");

                    b.Property<string>("Celular")
                        .HasColumnType("text")
                        .HasColumnName("Celular");

                    b.Property<string>("Celular2")
                        .HasColumnType("text")
                        .HasColumnName("Celula_2");

                    b.Property<DateTime?>("CheckIn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Check_in");

                    b.Property<string>("CheckInLocalizacion")
                        .HasColumnType("text")
                        .HasColumnName("Check_in_localizacion");

                    b.Property<string>("Cliente")
                        .HasColumnType("text")
                        .HasColumnName("Cliente");

                    b.Property<string>("CorreoPromotorVenta")
                        .HasColumnType("text")
                        .HasColumnName("Correo_promotor_venta");

                    b.Property<DateTime?>("CreadoEl")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Creado_el");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("text")
                        .HasColumnName("Creado_por");

                    b.Property<string>("Departamento")
                        .HasColumnType("text")
                        .HasColumnName("Departamento");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("Descripcion");

                    b.Property<string>("Distrito")
                        .HasColumnType("text")
                        .HasColumnName("Distrito");

                    b.Property<string>("Empresa")
                        .HasColumnType("text")
                        .HasColumnName("Empresa");

                    b.Property<string>("Estado")
                        .HasColumnType("text")
                        .HasColumnName("Estado");

                    b.Property<DateTime?>("FechaVisita")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Fecha_visita");

                    b.Property<DateTime?>("FinSolicitado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Fin_solicitado");

                    b.Property<string>("IT")
                        .HasColumnType("text")
                        .HasColumnName("IT");

                    b.Property<DateTime?>("InicioSolicitado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Inicio_solicitado");

                    b.Property<DateTime?>("ModificadoEl")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Modificado_el");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("text")
                        .HasColumnName("Modificado_por");

                    b.Property<string>("MotivoIncidente")
                        .HasColumnType("text")
                        .HasColumnName("Motivo_incidente");

                    b.Property<string>("NombreVia")
                        .HasColumnType("text")
                        .HasColumnName("Nombre_via");

                    b.Property<string>("NombreZona")
                        .HasColumnType("text")
                        .HasColumnName("Nombre_zona");

                    b.Property<string>("NotasInternas")
                        .HasColumnType("text")
                        .HasColumnName("Notas_internas");

                    b.Property<string>("Numero")
                        .HasColumnType("text")
                        .HasColumnName("Numero");

                    b.Property<string>("PaisRegion")
                        .HasColumnType("text")
                        .HasColumnName("Pais_region");

                    b.Property<string>("ProductosRegistrados")
                        .HasColumnType("text")
                        .HasColumnName("Productos registrados");

                    b.Property<string>("Provincia")
                        .HasColumnType("text")
                        .HasColumnName("Provincia");

                    b.Property<string>("Referencia")
                        .HasColumnType("text")
                        .HasColumnName("Referencia");

                    b.Property<string>("Tecnico")
                        .HasColumnType("text")
                        .HasColumnName("Tecnico");

                    b.Property<string>("TelefonoFijo")
                        .HasColumnType("text")
                        .HasColumnName("Telefono_fijo");

                    b.Property<string>("TipoServicio")
                        .HasColumnType("text")
                        .HasColumnName("Tipo_servicio");

                    b.Property<string>("Zona")
                        .HasColumnType("text")
                        .HasColumnName("Zona");

                    b.HasKey("ID");

                    b.ToTable("GACP_APP_TB_TICKETS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
